### ISSUE TITLE
How to I can add API Version to JSONAPILinks()

### ISSUE THREAD

**Issue by imhuytq** [google/jsonapi#112]
In my app, I have a struct that look similar to this:

```go
type Profile struct {
	ID          uint   `jsonapi:"primary,profile"`
	Name        string `jsonapi:"attr,name"`
	Description string `jsonapi:"attr,description"`
	Gender      string `jsonapi:"attr,gender"`
	Location    string `jsonapi:"attr,location"`
	Level       string `jsonapi:"attr,level"`
}

func (profile Profile) JSONAPILinks() *jsonapi.Links {
	return &jsonapi.Links{
		"self": fmt.Sprintf("/profiles/%d", profile.ID),
	}
}
```
I'm using Gin Web Framework. In `c *gin.Context`, I stored a key/value pair is: `c.Set("api-version", "something")`. How to can I get `api-version` in JSONAPILinks()?

**Comment by genexp** [comment]
As you mentioned, you'd need to either:
* store a pointer to some sort of global struct
* Have a new "payload" or other wrapper objects that decorates this one.  This is what we do.

**Comment by genexp** [comment]
PS: Not sure this is a bug or a feature.  It would work as exists, straight up go :)
