### ISSUE TITLE
Unable to run example app; undefined errors

### ISSUE THREAD

**Issue by myartsev** [google/jsonapi#126]
I get the following errors running the example app after following the all the setup instruction per the readme:
```
$ go run $GOPATH/src/github.com/google/jsonapi/examples/app.go
# command-line-arguments
src/github.com/google/jsonapi/examples/app.go:37:21: undefined: ExampleHandler
src/github.com/google/jsonapi/examples/app.go:46:17: undefined: headerAccept
src/github.com/google/jsonapi/examples/app.go:63:17: undefined: headerAccept
src/github.com/google/jsonapi/examples/app.go:78:10: undefined: fixtureBlogCreate
src/github.com/google/jsonapi/examples/app.go:84:17: undefined: headerAccept
src/github.com/google/jsonapi/examples/app.go:101:3: undefined: fixtureBlogCreate
src/github.com/google/jsonapi/examples/app.go:102:3: undefined: fixtureBlogCreate
src/github.com/google/jsonapi/examples/app.go:103:3: undefined: fixtureBlogCreate
src/github.com/google/jsonapi/examples/app.go:110:17: undefined: headerAccept
src/github.com/google/jsonapi/examples/app.go:125:22: undefined: Blog
src/github.com/google/jsonapi/examples/app.go:125:22: too many errors
```

_go version go1.9.2 linux/amd64
Debian GNU/Linux 9.3 (stretch)_

**Comment by nstratos** [comment]
In order to use `go run` you need to specify all the files. You can see it working if you use: 

    go run !(*_test).go

The recommended way is: 

    go build && ./examples

**Comment by myartsev** [comment]
I opened this issue on the very first day of playing around with Go; by now this all makes sense but for someone new to the language this commit is a good clarification. Thanks!

**Comment by The-Don-Himself** [comment]
Just ran into this as well, the suggestion above works. Hopefully, the PR can be merged soon. 
It's just a little bit demoralizing learning a new language then things don't work as documented out of the box.

**Comment by aren55555** [comment]
We just merged it, @nstratos thank you for your contribution!
