### ISSUE TITLE
ISO8601 timestamps are not fully supported.

### ISSUE THREAD

**Issue by sjauld** [google/jsonapi#145]
Currently, iso8601TimeFormat is defined as `2006-01-02T15:04:05Z`.

However, the iso8601 spec also allows for something like `2006-01-02T15:04:05-07:00`

Supporting both would be nice.

**Comment by aren55555** [comment]
Go's standard library type `time.Time` also has the same issue; it only supports RFC 3339 which is a smaller profile of ISO 8601 (see src here). If you need the full range of ISO 8601, I'd suggest implementing your own type that implements both the `json.Marshaler` and `json.Unmarshaler` interfaces. In this way you can handle the specific profiles of ISO 8601 that your application specifically desires.
