### ISSUE TITLE
How to implement links

### ISSUE THREAD

**Issue by FranciscoGJ** [google/jsonapi#152]
I do not understand how to implement the Linkable interface next to my struct.

I have the following struct
`type User struct {
	ID        int `jsonapi:"primary,users"`
	FirstName string `jsonapi:"attr,firstname"`
	Lastname string `jsonapi:"attr,lastname"`
	Email string `jsonapi:"attr,email"`
	Age int `jsonapi:"attr,age"`
}
`
I am using Gin as a webserver and I use jsonapi.Marshal (user) to generate the json response. How can I add links to the object response?

**Comment by DenLilleMand** [comment]
You should probably format your JSON correctly. 

If you have the user struct you can implement it like so:
```
// JSONAPILinks implements the Linkable interface for a user
func (user User) JSONAPILinks() *jsonapi.Links {
	return &jsonapi.Links{
		"self": fmt.Sprintf("https://example.com/users/%d", user.ID),
	}
}
```
When you marshal it, the links end up inside of the `data.links` object.
