### ISSUE TITLE
Are custom attribute types in the roadmap anymore?

### ISSUE THREAD

**Issue by botverse** [google/jsonapi#164]
@shwoodard first thanks for the fantastic work on this.

Now just to clarify:
- Are custom attribute types out of the scope now? 
- When can we expect them to be around?

In #163 @henrmota seems to have fixed the problem but in #159 you seem to have removed them from even the README.

I think I can say that there are some users interested on this based on the issues open atm.

Cheers.

**Comment by henrmota** [comment]
Hi, I hope my PR is merged, thankyou @botverse

**Comment by botverse** [comment]
@henrmota this also seems to work for me: https://github.com/google/jsonapi/commit/db5a629f000893842c4b2a9cdc733930811af44d

just testing for the struct to be of type `json.Unmashaler` otherwise trying to unmarshal it as a node

**Comment by botverse** [comment]
Closing as project is dead
