### ISSUE TITLE
Zero valued time.Time being omitted

### ISSUE THREAD

**Issue by abennett** [google/jsonapi#173]
Sorry if I'm wrong about this, but it looks like `time.Time` values that are "zero" values are being omitted from marshaling. I question if this should this be the desired behavior. Zero values are still useful, especially if you're trying to avoid passing around nils/nulls. Let me know what you think, and thank you for maintaining this.

https://github.com/google/jsonapi/blob/d0428f63eb511f08685bda2d0a6af1d7532fb1c0/response.go#L306-L308

**Comment by thilonel** [comment]
Hey, I think the omitempty configuration should help you in the model description.

**Comment by Ridzhi** [comment]
The same problem. 

`
type Request struct {
    BlockedUntil time.Time ``jsonapi:"attr,blocked_until,iso8601"``
}
`

If `BlockedUntil` had zero value, after marshaling field `BlockedUntil`  is omit. Expected behavior: `BlockedUntil` will remain after marshaling

**Comment by abennett** [comment]
I think we've all moved on with life.
