### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by challarao** [google/jsonapi#191]
Could someone declare the status of this project?

**Comment by mfcochauxlaberge** [comment]
No: https://github.com/google/jsonapi/issues/180#issuecomment-576893652

**Comment by challarao** [comment]
Thanks, @mfcochauxlaberge. I wish it is mentioned in the readme page.

**Comment by phamdt** [comment]
is there a company out there willing to sponsor a fork?

**Comment by aren55555** [comment]
I added a "No Maintenance Intended" badge to the homepage to hopefully better indicate that we (Google) don't intend to actively develop this project.
