### ISSUE TITLE
Does example in README have a typo?

### ISSUE THREAD

**Issue by Integralist** [google/jsonapi#196]
I think the hyphen in the example should actually be an underscore...

```diff
- Likes  uint   `jsonapi:"attr,likes-count,omitempty"`
+ Likes  uint   `jsonapi:"attr,likes_count,omitempty"`
```

**Comment by aren55555** [comment]
To be entirely correct by the spec, it should really be `likesCount` (see https://jsonapi.org/recommendations/#naming).
