### ISSUE TITLE
Unmarshalling Payload for jsonAPI PATCH

### ISSUE THREAD

**Issue by iderdik** [google/jsonapi#31]
When unmarshalling a payload for PATCH that only contains some of the fields, how do you recommend we differentiate between values not included in the PATCH and values included but blank. The resulting Go struct will initialize all fields to 0-values and this make it difficult to properly implement the json API patch as per http://jsonapi.org/format/#crud-updating

**Comment by aren55555** [comment]
@iderdik I'd suggest using pointers for fields that permit nil values.

```
type Car struct {
  ...
  PurchasedAt *time.Time `jsonapi:"attr,purchased_at"`
  ...
}
```

**Comment by iderdik** [comment]
Thanks, that should work.

**Comment by iderdik** [comment]
After changing the struct members to pointers, I now get:

```
{"errors":[{"status":400,"message":"data is not a jsonapi representation of '*models.xxxx'"}]}
```

I haven't changed anything else about the struct. Are pointers handle differently?

**Comment by aren55555** [comment]
@iderdik can you post an example of the struct you are trying to serialize/deserialize?

**Comment by iderdik** [comment]
@aren55555 Further research shows that this error happens when there are `*string` members in the struct. This is the line that panics: https://github.com/shwoodard/jsonapi/blob/master/request.go#L312

It looks like there might be a need for a check if `reflect.Kind()` is a pointer and handle appropriately.

**Comment by iderdik** [comment]
And this all seems to be dealt with in this PR :)  https://github.com/shwoodard/jsonapi/pull/28  Any chance that will get merged soon?

**Comment by aren55555** [comment]
@iderdik master now has the commits that support fields of `*string`
