### ISSUE TITLE
Need support for `omitempty` & `-` on attr fields.

### ISSUE THREAD

**Issue by thedodd** [google/jsonapi#33]
There are conditions where a model is used in different circumstances, for different responses, and a field may be present, or not present depending on the circumstance. Standard library supports the `omitempty` and `-` tokens in the `json:""` tag. It would be great to offer the same thing here.

Maybe a third value can be passed: `jsonapi:"attr,myfield,omitempty"` or something of the sort.

**Comment by aren55555** [comment]
Given a struct like:

```go
type Book struct {
	ID          int
	Author      string    `json:"author"`
	Title       string    `json:"title,omitempty"`
	PublishedAt time.Time `json:"-"`
}
```

You would expect JSON like: 

```json
{
    "ID": 1,
    "author": "aren55555"
}
```
Note the "title" key/value are only present if the Book.Title had a value.

**When it comes to the `jsonapi` struct field tag; there is no `-` option as fields without a `jsonapi` are simply ignored.**

```go
type Book struct {
	ID          int    `jsonapi:"primary,books"`
	Author      string `jsonapi:"attr,author"`
	Title       string `jsonapi:"attr,title,omitempty"`
	PublishedAt time.Time
}
```

```json
{
    "data": {
        "type": "books",
        "id": "1",
        "attributes": {
            "author": "aren55555",
        }
    }
}
```

**However as it currently stands the `omitempty` option only actually works on `Struct` fields of the ` type.**

**Comment by thedodd** [comment]
Ahh. That is the issue I was running into then. For non-string type fields, I was observing that it did not work. I'd be happy to create a PR which will `omitempty` fields of other types with their zero-value. Thoughts?

**Comment by aren55555** [comment]
@thedodd I had already started on this yesterday; here is the Pull Request: https://github.com/shwoodard/jsonapi/pull/35

**Comment by thedodd** [comment]
@aren55555 you rock. Looking now.
