### ISSUE TITLE
Nested structs not being Unmarshaled

### ISSUE THREAD

**Issue by iderdik** [google/jsonapi#49]
Given a struct that contains another struct:
```
type Address struct {
	City string `jsonapi:"attr,city" json:"city"`
	State string `jsonapi:"attr,state" json:"state"`
}

type AdditionalInfo struct {
	HomeAddress     *Address `jsonapi:"attr,homeaddress" json:"homeaddress"`
        Phone                  *string     `jsonapi:"attr,phone" json:"phone"`
}
```

When calling `UnmarshalPayload` with this json:
```
{
    "homeaddress": {
        "city": "brooklyn",
        "state": "NY"
    },
    "phone": "555-555-5555"
}
```

I get an error `data is not a jsonapi representation of AdditionalInfo`. Are nested structs not supported?

**Comment by aren55555** [comment]
Your payload is not valid JSON API; even if it was (see below) I don't believe the nested struct is supported.

```json
{
    "data": {
        "type": "info",
        "attributes": {
            "phone": "555-555-5555",
            "homeaddress": {
                "city": "brooklyn",
                "state": "NY"
            }
        }
    }
}
```

If you want, please submit a PR adding support for this feature.

**Comment by iderdik** [comment]
Sorry about that - my actual json was valid jsonAPI, I had just extracted the relevant part of the `attributes` key.

In any case, I seem to have gotten the functionality I need by declaring the type of HomeAddress to  be a `map[string]interface{}` and handling any conversions between `map` and `struct` elsewhere. It's obviously not ideal but it's all I have right now.

**Comment by bensullivan** [comment]
+1 for this feature please

**Comment by shwoodard** [comment]
Dup of https://github.com/google/jsonapi/issues/21

**Comment by iderdik** [comment]
#21 is more about embedded anonymous structs. This issue is about structs as a field in a struct.

**Comment by msabramo** [comment]
See #99 and https://github.com/Slemgrim/jsonapi/pull/3, which fixes pointers to struct fields.
