### ISSUE TITLE
Unmarshal relationships with null data

### ISSUE THREAD

**Issue by nstratos** [google/jsonapi#61]
Greetings,

I am trying to unmarshal a payload that includes relationships with null data like this one:
```json
{
   "data":{
      "type":"movie",
      "id":"1",
      "relationships":{
         "cast":{
            "data":[
               {
                  "type":"cast",
                  "id":"5"
               },
               {
                  "type":"cast",
                  "id":"6"
               }
            ]
         }
      }
   },
   "included":[
      {
         "type":"cast",
         "id":"5",
         "relationships":{
            "person":{
               "data":null
            }
         }
      },
      {
         "type":"cast",
         "id":"6",
         "relationships":{
            "person":{
               "data":{
                  "type":"person",
                  "id":"33"
               }
            }
         }
      },
      {
         "type":"person",
         "id":"33",
         "attributes":{
            "name":"john"
         }
      }
   ]
}
```

According to the JSON API spec, a resource linkage can be [null for empty to-one relationships](http://jsonapi.org/format/#document-resource-object-linkage).

For convenience I've added some code that tries to unmarshal such a payload on the [Go playground](https://play.golang.org/p/iyqcggoHgx).

When using `jsonapi.UnmarshalPayload` or `jsonapi.UnmarshalManyPayload` to handle payload like the above, the error `data is not a jsonapi representation of 'xxx'` is returned.

The culprit seems to be [this line](https://github.com/google/jsonapi/blob/master/request.go#L538) which receives a `nil` `relationships.Data` from [this line](https://github.com/google/jsonapi/blob/master/request.go#L514). A nil check fixed the problem for my case but there might be other areas in the package that are affected so I figured I should report it here.

Thank you

**Comment by aren55555** [comment]
This is a known issue see https://github.com/google/jsonapi/pull/43
