### ISSUE TITLE
Unmarshalling an array of objects?

### ISSUE THREAD

**Issue by ChrisCooney** [google/jsonapi#67]
If I've got an array back as my Json body, and I want to unmarshal that into an array of structs, it appears, according to your docs, that I can't do this. Is this feature coming soon?

**Comment by aren55555** [comment]
There is a way it's just not documented (yet). See https://github.com/google/jsonapi/pull/66 for the UnmarshalMany docs. There are examples in that pr that should set you down the right path.

**Comment by aren55555** [comment]
@ChrisCooney here is some sample code taken from the Readme:

```go
type Blog struct{}

func(w http.ResponseWriter, r *http.Request) {
	blogs, err := UnmarshalManyPayload(r.Body, reflect.TypeOf(new(Blog)))
	if err != nil {
		t.Fatal(err)
	}

	for _, blog := range blogs {
		b, ok := blog.(*Blog)
		// ...do something with each of your blogs
	}
}
```

**Comment by ChrisCooney** [comment]
Nice spot mate.
