### ISSUE TITLE
UnmarshalManyPayload with Links 

### ISSUE THREAD

**Issue by edisonspencer** [google/jsonapi#68]
Hi,

I've been trying to use the jsonapi for marshaling and unmarshaling a JSON object containing links, and I am able to marshal the JSON object (and have the links section in it), however, I am not able to unmarshal and extract the link from the JSON object.

I am unable to find any code sample, even in the tests, to see how it could be done. Is this information lost when the unmarshal is done through this library? is there any workaround which is not clear?

Thanks.

**Comment by ChrisCooney** [comment]
It's insane how this can be considered useable without the ability of deserialising a list of objects.

**Comment by aren55555** [comment]
@edisonspencer there is currently no one liner way to unmarshal a payload of the form:

```
"data": [...], 
"links": {...}
```

However you can do something like:

```go
payload := new(ManyPayload)
if err = json.NewDecoder(in).Decode(payload); err != nil {
	t.Fatal(err)
}
```

And payload.Links should contain the Links Object at the `"links"` top level member. See this test for a more complete example: https://github.com/google/jsonapi/blob/master/request_test.go#L553

**Comment by rberlind** [comment]
I believe the link in https://github.com/google/jsonapi/issues/68#issuecomment-275572468 should be https://github.com/google/jsonapi/blob/master/request_test.go#L694

**Comment by rberlind** [comment]
Also, it would be more helpful to have a working example that demarshalled a structure that used jsonapi structure tags.
