### ISSUE TITLE
omitempty for primary ID

### ISSUE THREAD

**Issue by mitchellh** [google/jsonapi#83]
I'm using jsonapi to construct jsonapi documents as an API _client_ and when marshaling a resource for creation I'd like to omit the "id" since the implementation I'm using requires that (and appears spec compliant as far as I can tell). 

To do this at the moment I have to reimplement `OnePayload` to have omitempty on the ID manually.

**Comment by aren55555** [comment]
As a client this is definitely a valid scenario. You construct the entity client side, and when the server saves the entity it assigns and returns the `id`.

This library was originally abstracted out of a project where our original use case was a go jsonapi server. As such, we only considered the server use case for the `id` field.

With that being said it should not be that hard to add the omitempty feature to the `id` annotation. If you want to take a stab at it, I'd be happy to review your pull request. Otherwise it may be a few weeks before I can spend time on this.

**Comment by mitchellh** [comment]
For me its as simple as adding `omitempty` to the ID field of `Node`, but I'm not sure of the ramifications of this. Do you think this would negatively affect any usage? I haven't read the spec carefully enough to be 100% certain...

If you think that's all it takes I'd be happy to make that PR.

**Comment by aren55555** [comment]
Initially I thought we would allow the developer to annotate their structs' `id` field with `omitempty`. However (as far as I'm aware) I don't see why you would ever want to send an empty `id`; example: 

```json
{
    "data": {
        "type": "foo",
        "id": "",
        "attributes": {...}
    }
}
```

Which means it is seemingly OK to annotate `Node`'s `ID` field with a vanilla json `omitempty`.

Thoughts @shwoodard ?

**Comment by mitchellh** [comment]
Right, and the other issue is even if we could just annotate `jsonapi:"primary,type,omitempty"`, because `Node` doesn't have omitempty on ID, it would still transmit a blank ID. So eventually we'd have to get there anyways. :)

**Comment by mitchellh** [comment]
Just going to leave this here in case anyone has this issue at the moment and needs a workaround. It isn't ideal for a lot of reasons but it does work, and is easy to see how to translate to Many payloads as well:

```go
func Marshal(w io.Writer, m interface{}) error {
	payload, err := jsonapi.MarshalOne(m)
	if err != nil {
		return err
	}

	// We don't want to send any included, since the TFE API doesn't use it.
	payload.Included = nil

	// "final" is what we're going to encode. If we have a blank ID, then
	// we have to do some hoop-jumping to make sure it doesn't show up in the
	// request.
	final := m
	if payload.Data.ID == "" {
		// Marshal to an in-memory buffer first to allow us to do replacement.
		var buf bytes.Buffer
		if err := json.NewEncoder(&buf).Encode(payload); err != nil {
			return err
		}

		// Delete the ID from the data
		var temp map[string]interface{}
		if err := json.NewDecoder(&buf).Decode(&temp); err != nil {
			return err
		}
		tempData := temp["data"].(map[string]interface{})
		delete(tempData, "id")

		// Set the final thing to encode to be our temp that has no ID
		final = temp
	}

	// Re-encode
	return json.NewEncoder(w).Encode(final)
}
```
