### ISSUE TITLE
Support customizing output format for time.Time

### ISSUE THREAD

**Issue by msabramo** [google/jsonapi#91]
Current code takes `time.Time` values and writes that out as UNIX epoch times (integers).

It would be nice if I could specify (in the struct tag?) that I just want the time as-is, which shows a nice human-readable time instead of an integer.

**Comment by aren55555** [comment]
The JSON API specification recommends that date and time fields use ISO 8601 format: http://jsonapi.org/recommendations/#date-and-time-fields

For example:

```go
type Blog struct {
    ID            int       `jsonapi:"primary,blogs"`
    CreatedAt     time.Time `jsonapi:"attr,created_at,iso8601"`
}
```

**Comment by aren55555** [comment]
@msabramo I looked into this further and I don't think it is a good idea to implement. Say you wanted a date like `Feb 3, 2013 at 7:54pm (PST)` the golang `time.Parse` implementation would need to look like: 

```go
const longForm = "Jan 2, 2006 at 3:04pm (MST)"
t, _ := time.Parse(longForm, "Feb 3, 2013 at 7:54pm (PST)")
fmt.Println(t)
```

Now what you would need to put into the JSON API annotation tag would be something like:

```go
type Blog struct {
    ID            int       `jsonapi:"primary,blogs"`
    CreatedAt     time.Time `jsonapi:"attr,created_at,Jan 2, 2006 at 3:04pm (MST)"`
}
```

However the comma after `Jan 2` would cause the tag parser to break. There is no way to escape the requisite comma.
