### ISSUE TITLE
the godoc url in the project description is pointing to other repo

### ISSUE THREAD

**Issue by muly** [google/jsonapi#96]
please fix: replace `http://godoc.org/github.com/shwoodard/jsonapi` with `http://godoc.org/github.com/google/jsonapi`

**Comment by aren55555** [comment]
The project was previously under Sam's (`shwoodard`) GitHub account. If you are looking at master the links in the Readme should all be correct. If you are looking at older branches the links may point to the `shwoodard` godoc URLs.
